/**:
  ros__parameters:
    device: /dev/ttyUSB0
    baudrate: 1000000
    include_gripper: true

    # publish rate for /joint_states
    state_rate_hz: 50.0

    # gentle startup ramp
    startup_slow_vel: 30     # Profile Velocity, units of 0.229 rev/min
    startup_slow_acc: 10     # Profile Accel, units of 214.577 rev/min^2
    settle_seconds: 0.5      # how long torque holds at slow profile before ramp

    # operating profile after startup
    run_vel: 100
    run_acc: 30

    # IK preference
    elbow_up: true
